[project]
name = 'main'

[skills]
[skills.mn-github-pr-review]
git = 'https://github.com/manusa/ai.git'
path = 'dotfiles/.claude/skills/mn-github-pr-review'
ref = 'main'

[mcpServers]
[mcpServers.git]
transport = 'stdio'
name = 'git'
url = 'uv:mcp-server-git'

[mcpServers.playwright]
transport = 'stdio'
name = 'playwright'
url = 'npm:@playwright/mcp@latest'
